name: 'Terraform Plan and Apply'

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}     
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform_plan:
    name: 'Terraform Plan Job'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout the rpository
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with: 
        creds: ${{ secrets.AZURE_CREDENTIALS }}  

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Save Plan output
      uses: actions/upload-artifact@v4
      with: 
        path: tfplan
        name: tfplan
        
  terraform_apply:
    name: 'Terraform Apply Job'
    runs-on: ubuntu-latest
    needs: terraform_plan

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout the rpository
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with: 
        creds: ${{ secrets.AZURE_CREDENTIALS }}  

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Download plan output
      uses: actions/download-artifact@v4
      with: 
        name: tfplan

    - name: Terraform Plan
      run: terraform plan -out=tf          